package:
  name: openmm
  version: 7.4.0

source:
  git_url: https://github.com/pandegroup/openmm.git

  patches:
    #- silent-cmake.patch
    - silent-doxygen.patch
    - silent-latexpdf.patch

extra:
  #upload: betacuda{{ CUDA_SHORT_VERSION }}{{ ",beta" if CUDA_SHORT_VERSION == "92" else ""}}
  #upload: devcuda{{ CUDA_SHORT_VERSION }}{{ ",dev" if CUDA_SHORT_VERSION == "92" else ""}}
  upload: cuda{{ CUDA_SHORT_VERSION }}{{ ",main" if CUDA_SHORT_VERSION == "92" else ""}}
  force_upload: True

build:
  number: 0
  skip: True # [win]
  detect_binary_files_with_prefix: False
  #string: py{{ py }}_cuda{{ CUDA_SHORT_VERSION }}_{{ environ.get("GIT_DESCRIBE_HASH", "")[1:8] }}_1 # this doesn't work with conda-build-all
  string: py{{ py }}_cuda{{ CUDA_SHORT_VERSION }}_1
  #features:
  #  - cuda{{ CUDA_SHORT_VERSION }}

requirements:
  build:
    # on windows, need to install cmake manually
    - cmake     [not win]
    - jom       [win]
    - python
    # Pin fftw3f to 3.3.3 to work around OSX py34 issues
    - fftw3f ==3.3.3 [osx]
    - fftw3f ==3.3.4 [win or linux]
    # swig is pinned to use omnia swig 3.0.8
    - swig ==3.0.8
    # on osx, need to install doxygen manually
    - doxygen   [not osx]
    # for building docs
    - sphinx
    - sphinxcontrib-bibtex
    - sphinxcontrib-lunrsearch >=0.3
    - sphinxcontrib-autodoc_doxygen
    - lxml
    - numpy
    # Get clang from conda-forge
    - clangdev ==7.0.0 [linux]
    # Required for sphinx
    - latexmk

  run:
    - python
    - fftw3f
    - numpy

#test:
#  requires:
#    - python
#    - cuda{{ CUDA_SHORT_VERSION }}
#  imports:
#    - simtk
#    - simtk.openmm
#  commands:
#    - python -m simtk.testInstallation

about:
  home: http://openmm.org
  license: MIT
  summary: A high performance toolkit for molecular simulation.
